services:
  # 1. Le service Base de Données (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql_gel
    restart: always
    environment:
      MYSQL_DATABASE: smartgel_db
      MYSQL_ROOT_PASSWORD: root_password
    # On map le port 3306 du conteneur vers 3307 de ton PC 
    # pour éviter le conflit "Address already in use"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql # Pour garder les données même si tu éteins Docker
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 2. L'interface graphique pour gérer la BDD (PhpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_gel
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

  # 3. Ton API (Node.js) qui sera utilisée par l'App Android et le Site Web
  api:
    build: .
    container_name: node_api_mock
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root_password
      DB_NAME: smartgel_db
      PORT: 3000

# Volume pour la persistance des données
volumes:
  db_data: